In [70]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np

In [71]:
relative_coords_h = torch.arange(-(3 - 1), 3, dtype=torch.float32)
relative_coords_w = torch.arange(-(3 - 1), 3, dtype=torch.float32)
relative_coords_table = torch.stack(torch.meshgrid([relative_coords_h,
                            relative_coords_w])).permute(1, 2, 0).contiguous().unsqueeze(0)
print(relative_coords_h, relative_coords_w)
print(relative_coords_table.shape)


tensor([-2., -1.,  0.,  1.,  2.]) tensor([-2., -1.,  0.,  1.,  2.])
torch.Size([1, 5, 5, 2])


In [72]:
relative_coords_table[:, :, :, 0] /=(3-1)
relative_coords_table[:, :, :, 1] /=(3-1)
print(relative_coords_table)

tensor([[[[-1.0000, -1.0000],
          [-1.0000, -0.5000],
          [-1.0000,  0.0000],
          [-1.0000,  0.5000],
          [-1.0000,  1.0000]],

         [[-0.5000, -1.0000],
          [-0.5000, -0.5000],
          [-0.5000,  0.0000],
          [-0.5000,  0.5000],
          [-0.5000,  1.0000]],

         [[ 0.0000, -1.0000],
          [ 0.0000, -0.5000],
          [ 0.0000,  0.0000],
          [ 0.0000,  0.5000],
          [ 0.0000,  1.0000]],

         [[ 0.5000, -1.0000],
          [ 0.5000, -0.5000],
          [ 0.5000,  0.0000],
          [ 0.5000,  0.5000],
          [ 0.5000,  1.0000]],

         [[ 1.0000, -1.0000],
          [ 1.0000, -0.5000],
          [ 1.0000,  0.0000],
          [ 1.0000,  0.5000],
          [ 1.0000,  1.0000]]]])


In [73]:
relative_coords_table[:, :, :, 0] *= 8
relative_coords_table = torch.sign(relative_coords_table)* torch.log2(
    torch.abs(relative_coords_table) + 1.0) / np.log2(8)
print(relative_coords_table)

tensor([[[[-1.0566, -0.3333],
          [-1.0566, -0.1950],
          [-1.0566,  0.0000],
          [-1.0566,  0.1950],
          [-1.0566,  0.3333]],

         [[-0.7740, -0.3333],
          [-0.7740, -0.1950],
          [-0.7740,  0.0000],
          [-0.7740,  0.1950],
          [-0.7740,  0.3333]],

         [[ 0.0000, -0.3333],
          [ 0.0000, -0.1950],
          [ 0.0000,  0.0000],
          [ 0.0000,  0.1950],
          [ 0.0000,  0.3333]],

         [[ 0.7740, -0.3333],
          [ 0.7740, -0.1950],
          [ 0.7740,  0.0000],
          [ 0.7740,  0.1950],
          [ 0.7740,  0.3333]],

         [[ 1.0566, -0.3333],
          [ 1.0566, -0.1950],
          [ 1.0566,  0.0000],
          [ 1.0566,  0.1950],
          [ 1.0566,  0.3333]]]])


In [74]:
coords_h = torch.arange(3)
coords_w = torch.arange(3)
coords = torch.stack(torch.meshgrid([coords_h, coords_w]))  # 2, Wh, Ww
coords_flatten = torch.flatten(coords, 1)  # 2, Wh*Ww
print(coords_flatten)
relative_coords = coords_flatten[:, :, None] - coords_flatten[:, None, :]

tensor([[0, 0, 0, 1, 1, 1, 2, 2, 2],
        [0, 1, 2, 0, 1, 2, 0, 1, 2]])


In [75]:
qkv = nn.Linear(2, 2*3)
B_, N, dim = 2, 4, 2
x = torch.randn(B_,N,dim)
print(x.shape)
print(qkv.weight)
qkv = F.linear(input=x, weight=qkv.weight)
qkv.shape

torch.Size([2, 4, 2])
Parameter containing:
tensor([[-0.2493,  0.4401],
        [-0.6490, -0.4440],
        [-0.0708, -0.1819],
        [ 0.4652, -0.4327],
        [-0.2247,  0.1471],
        [-0.4173,  0.4423]], requires_grad=True)


torch.Size([2, 4, 6])